services:
  learning-mysql-container:
    container_name: learning-mysql-container
    hostname: learning-mysql-container
    image: mysql:8.0.30-oracle
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=default
    ports:
      - '3306:3306'
    healthcheck:
      test: mysql -h learning-mysql-container -u root -p123456 -e "SELECT 1" || exit 1
    volumes:
      - learning-mysql-data:/var/lib/mysql

volumes:
  learning-mysql-data: